// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaEPI.Data;

#nullable disable

namespace SistemaEPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260423162405_AdicionandoColunaDeletedAt")]
    partial class AdicionandoColunaDeletedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("SistemaEPI.Models.EntregaEpi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssinaturaDigitalHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataEntrega")
                        .HasColumnType("TEXT");

                    b.Property<int>("EpiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ProximaTroca")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResponsavelRegistroId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EpiId");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("ResponsavelRegistroId");

                    b.ToTable("EntregasEpi");
                });

            modelBuilder.Entity("SistemaEPI.Models.Epi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroCA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PeriodicidadeTrocaDias")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ValidadeCA")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Epis");
                });

            modelBuilder.Entity("SistemaEPI.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("SistemaEPI.Models.Treinamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataConclusao")
                        .HasColumnType("TEXT");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeNR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResponsavelRegistroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusVencimento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ValidadeMeses")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("ResponsavelRegistroId");

                    b.ToTable("Treinamentos");
                });

            modelBuilder.Entity("SistemaEPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NivelAcesso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaEPI.Models.EntregaEpi", b =>
                {
                    b.HasOne("SistemaEPI.Models.Epi", "Epi")
                        .WithMany()
                        .HasForeignKey("EpiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaEPI.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaEPI.Models.Usuario", "ResponsavelRegistro")
                        .WithMany()
                        .HasForeignKey("ResponsavelRegistroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Epi");

                    b.Navigation("Funcionario");

                    b.Navigation("ResponsavelRegistro");
                });

            modelBuilder.Entity("SistemaEPI.Models.Treinamento", b =>
                {
                    b.HasOne("SistemaEPI.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaEPI.Models.Usuario", "ResponsavelRegistro")
                        .WithMany()
                        .HasForeignKey("ResponsavelRegistroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("ResponsavelRegistro");
                });
#pragma warning restore 612, 618
        }
    }
}
